### ISSUE TITLE
Strange usage scenario with browserify

### ISSUE THREAD

**Issue by mallim** [components/handlebars.js#15]
**Objective:** able to expose handlebars outside of bundle.js such that the other scripts can do a require("handlebars)

**Question:** Is this the correct way? Are there any better ways of doing this? As there is no problem doing a setup with jquery, moment etc

**How this being done**
- bower install handlebars
- npm install handlebars
- grunt-browserify is being setup as below:

``` javascript
    browserify: {
      top_libs:{
        src:[
          'other_source.js'
        ],
        dest:'target.js',
        options:{
          plugin:["minifyify"],
          transform:["debowerify"],
          alias:[
            'handlebars/dist/handlebars.js:handlebars'
          ],
          preBundleCB: function (b) {
            b.require('handlebars', {expose: 'handlebars'});
          }
        }
      }
    }
```

**Comment by nknapp** [comment]
I don't know too much about browserify, but it seems strange to use it together with bower.

Given the fact that this question is now three years old, I'll close it. Please add a comment if you still need an answer.
