### ISSUE TITLE
Build for 4.0.6 missing.

### ISSUE THREAD

**Issue by AlbertWillemsen-Centric** [components/handlebars.js#20]
Please advise.

**Comment by simongareste** [comment]
I would submit a pull request, but I'm not sure where you get these from. Comparing components from https://github.com/wycats/handlebars.js.git doesn't seem to be the solution. If you have some info, I'm willing to build it and make a PR

**Comment by AlbertWillemsen-Centric** [comment]
Same here.

**Comment by nknapp** [comment]
It's in the `dist/components`-directory after running `grunt build release`.
This whole repository is there :astonished:. I'll open a PR.
