### ISSUE TITLE
This package needs refactoring/update

### ISSUE THREAD

**Issue by ivantcholakov** [components/handlebars.js#27]
"Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead."

**Comment by jaylinski** [comment]
All other alternatives also seem to be abandoned: https://github.com/RobLoach/component-installer#deprecated

Best alternative seems to be https://asset-packagist.org/.

**Comment by RobLoach** [comment]
Thanks @jaylinski :+1:
